[package]
name = "p3-multilinear-util"
description = "A collection of utility functions and tools for multilinear operations."
version.workspace = true
edition.workspace = true

[features]
parallel = ["p3-maybe-rayon/parallel"]

[dependencies]
itertools.workspace = true
p3-field = { path = "../field" }
p3-matrix = { path = "../matrix" }
p3-maybe-rayon = { path = "../maybe-rayon" }
p3-util = { path = "../util" }
serde = { workspace = true, features = ["derive", "alloc"] }

rand.workspace = true